### ISSUE TITLE
Add Banners to site

### ISSUE THREAD

**Issue by youngtag** [domurtag/festivals#26]
![web-banner300-250-48](https://cloud.githubusercontent.com/assets/10478450/7145495/6d7ed7ca-e2e4-11e4-8d0e-49d4f6dcabc7.jpg)
![banner-long-48](https://cloud.githubusercontent.com/assets/10478450/7145496/6ee55fc6-e2e4-11e4-9283-9c13e278864d.jpg)

Hi,

Please add attached banners.

The 728*90 appearing on the top of all pages in between grey nav and main blue nav.

The 300*250 appearing where the map is, or if you're not happy with that, below beside where twitter appears.

Thanks

**Comment by youngtag** [comment]
Oh and importantly please direct all clicks through to

https://townlandscarnival.com/

**Comment by domurtag** [comment]
> The 300*250 appearing where the map is, or if you're not happy with that, below beside where twitter appears.

This means in the space to the right of the "Similar Festivals" box. If a festival has a Twitter feed and a YouTube video there won't be a space, so just don't show it in these cases.
