### ISSUE TITLE
Urgent - new banners to run for the weekend

### ISSUE THREAD

**Issue by youngtag** [domurtag/festivals#30]
Hi Donal,

Can you run the attached linking through to https://www.townlandscarnival.com/ from now until 12/05 please?

https://mail.google.com/mail/u/0/?ui=2&ik=48cc84f117&view=att&th=14d336bf360e4ec7&attid=0.2&disp=safe&realattid=162dfedb4a1c7ff4_0.1.5&zw
https://mail.google.com/mail/u/0/?ui=2&ik=48cc84f117&view=att&th=14d336bf360e4ec7&attid=0.3&disp=safe&realattid=162dfedb4a1c7ff4_0.1.7&zw

**Comment by domurtag** [comment]
The links don't work for me, it looks like they're links into your email which might be why you can access them but I can't. Also, can you be a bit more explicit about where you want the images to be placed?

**Comment by youngtag** [comment]
I did drag and drop but it's not worked for some reason so I emailed you the banners.

They are the exact same placements as previously, just a like for like replacement. Thanks
