### ISSUE TITLE
Installing the app locally

### ISSUE THREAD

**Issue by kkoci** [domurtag/festivals#39]
Hi, I wonder if there is a more explicit wiki in order to install this app on my local environment, I already have Grails 2.5.1 and MySQL set up.

I was trying to run it, by executing ./grailsw on project's root folder.

But it keeps giving me an error.

This one:

`./grailsw compile
Exception in thread "main" java.lang.ClassNotFoundException: org.codehaus.groovy.grails.cli.support.GrailsStarter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:90)
`

Any idea of what could it be?

Thanks in advance!

**Comment by donalmurtagh** [comment]
> if there is a more explicit wiki in order to install this app on my local environment

There is not.

I never tried using the Grails wrapper to start the app. Have you tried starting it with `grails run-app` instead.

**Comment by kkoci** [comment]
Hi @donalmurtagh yeah, just tried with that, and it worked, well, somehow

I'm sorry I'm fairly new to grails, obviously gave me an hibernate error about MySQL, gotta look for the database settings and fix them accordingly

Thank You very much

**Comment by donalmurtagh** [comment]
If you just create an empty database i.e. `create database festival`, the tables should be automatically created when the application starts.

**Comment by kkoci** [comment]
Wow, awesome, gotta try inside mysql, thank you

**Comment by donalmurtagh** [comment]
if you already created a festival database, drop it first with `drop database festival`

**Comment by kkoci** [comment]
Thank You very much

**Comment by domurtag** [comment]
You're welcome, feel free to post additional comments in this thread if you have any other problems running it

**Comment by kkoci** [comment]
Hi again, I'm sorry, I've created the database inside mysql

But, I think the app should have `application.groovy` or `application.yml` files, I can't find them

Maybe I should create them on grails-app/conf?

**Comment by kkoci** [comment]
I have created an application.groovy file, a basic one, with root user password, etc

This is the trace:

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)
	... 4 more
`

I think I'm missing something, this is my application.groovy

`dataSource {
    pooled = true
    dbCreate = "update"
    url = "jdbc:mysql://localhost:3306/festival"
    driverClassName = "com.mysql.jdbc.Driver"
    dialect = org.hibernate.dialect.MySQL5InnoDBDialect
    username = "root"
    password = "password"
    properties {
       jmxEnabled = true
       initialSize = 5
       maxActive = 50
       minIdle = 5
       maxIdle = 25
       maxWait = 10000
       maxAge = 10 * 60000
       timeBetweenEvictionRunsMillis = 5000
       minEvictableIdleTimeMillis = 60000
       validationQuery = "SELECT 1"
       validationQueryTimeout = 3
       validationInterval = 15000
       testOnBorrow = true
       testWhileIdle = true
       testOnReturn = false
       jdbcInterceptors = "ConnectionState;StatementCache(max=200)"
       defaultTransactionIsolation = java.sql.Connection.TRANSACTION_READ_COMMITTED
    }
}`

Any ideas? Thank You again

**Comment by domurtag** [comment]
No `applicaton.yaml` and `application.groovy` are for Grails 3 apps, this is a Grails 2 app.

**Comment by kkoci** [comment]
Hi @domurtag sorry for the delay, no, I'm learning grails, and it looks really interesting as a learning subject, it reminds me back when I was laerning rails :)

Thank You very much, I'm going to re-read the `README.md`
